spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/besteducation?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    password: dbuser
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    mode: HTML

